### ISSUE TITLE
ask about image transparent

### ISSUE THREAD

**Issue by teklidodo** [Mazhar004/MODNet-BGRemover#4]
Hello, I want to ask. how to make background image transparent? i need transparent background image png. Thank You

**Comment by Mazhar004** [comment]
Add alpha channel (for background transparent) while image saving. Though I haven't tried at my own, but thanks for qus I will add this feature into my code in next commit

**Comment by Mazhar004** [comment]
I have updated the code base, Now the system will generate a png image with transparent background

https://github.com/Mazhar004/MODNet-BGRemover/commit/9863d0480dfa7835dba5fc54a8e140206b5b83f6

**Comment by teklidodo** [comment]
oko Thank You

Pada tanggal Sel, 27 Apr 2021 pukul 22.12 Mazhar Hossain <
***@***.***> menulis:

**Comment by teklidodo** [comment]
Hello, I want ask again. I need to change resolution image because i want
use image to print. can you help me? Thank you

Pada tanggal Sel, 27 Apr 2021 pukul 22.12 Mazhar Hossain <
***@***.***> menulis:
