### ISSUE TITLE
Removing white Background

### ISSUE THREAD

**Issue by tushar-31093** [Mazhar004/MODNet-BGRemover#9]
Hi,
I am using the code to remove a white background from the image but the results are not as expected. Any ideas on how to make it work. Attaching the result.

Resulant image
![0001](https://user-images.githubusercontent.com/40886260/174451851-49ad3bc0-473b-4dee-9320-484aeaa7d422.png)

Original image
![0001](https://user-images.githubusercontent.com/40886260/174451856-6e88c72d-76ac-4f89-80a4-3da9325f268f.jpeg)

**Comment by Mazhar004** [comment]
Issue has been resolved
![a](https://user-images.githubusercontent.com/37472841/174471226-9f5cff34-c46c-4f1a-a08e-b30199e3c33d.png)

Use the latest code
